[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'vim-scripts/LanguageTool'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'nsf/gocode'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'w0rp/ale'
