[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c']

#tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = ['rust']
hook_add = '''
let g:deoplete#sources#rust#racer_binary='/usr/local/bin/racer'
let g:deoplete#sources#rust#rust_source_path='/usr/local/Cellar/rust/1.25.0/lib/rustlib/src/rust/src'
'''

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = ['c']

[[plugins]]
repo = 'ElmCast/elm-vim'
on_ft = ['elm']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['ex', 'exs', 'eex', 'leex']

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
on_ft = ['jl']

[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'
on_ft = ['php']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kt']

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']
hook_add = '''
let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords
'''

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['jsx', 'javascript']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'css'
hook_add = '''
au BufRead,BufNewFile *.scss set filetype=scss.css
'''

# build できない場合は、$HOME/.config/nvim/repos/github.com/mhartington/nvim-typescriptのinstall.shをrunする
[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = ['tsx', 'typescript']
build = 'bash install.sh'

[[plugins]]
repo = 'takkii/totolot'
on_ft = ['ruby']

[[plugins]]
repo = 'takkii/ruby-dictionary3'
on_ft = ['ruby']

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby']
