[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = ['csv']
hook_source = '''
" for chrisbra/csv
let g:csv_delim=','
let g:csv_highlight_column = 'y'
let g:csv_hiGroup = 'Visual'
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown']
