[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']
hook_add = '''
let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords
'''

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['jsx', 'javascript']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'css'
hook_add = '''
au BufRead,BufNewFile *.scss set filetype=scss.css
'''

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby']

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = ['csv']
hook_source = '''
" for chrisbra/csv
let g:csv_highlight_column = 'y'
let g:csv_hiGroup = 'Visual'
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown']
