[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:go_fmt_fail_silently = 1
  let g:ale_fix_on_save = 1
  " let g:neomake_javascript_enabled_makers = ['tslint', 'eslint', 'flow']

  " let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
  function! ALEStatus()
    " return ALEGetStatusLine()
    let l:counts = ale#statusline#Count(bufnr(''))

    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors

    return l:counts.total == 0 ? 'OK' : printf(
		    \   '⚠ %d ⨉ %d',
		    \   all_non_errors,
		    \   all_errors
		    \)
  endfunction

  let g:ale_linters = {'javascript': ['eslint'], 'jsx': ['stylelint', 'eslint'], 'tsx': ['tslint', 'prettier'], 'hs': ['hlint']}
  let g:ale_linter_aliases = {'jsx': 'css'}
  let g:ale_fixers = {
  \   'python': ['autopep8', 'isort'],
  \   'javascript': ['eslint'],
  \   'typescript': ['tslint', 'prettier'],
  \}
  let g:ale_fix_on_save = 1
  let g:ale_javascript_prettier_options = '--single-quote --trailing-comma es5'
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 1
  let g:ale_open_list = 1

  " エラーと警告がなくなっても開いたままにする
  " let g:ale_keep_list_window_open = 1
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<denite<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  " 参考:http://replicity.hateblo.jp/entry/2017/06/03/140731
  "
  "C-j,C-kで上下移動
  call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')
  "ESCキーでdeniteを終了
  call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
  call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')

  " C-sでsplit表示
  call denite#custom#map('insert', '<C-s>', '<denite:do_action:vsplit>', 'noremap')

  " tabopen
  call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>', 'noremap')

  " プロンプトの左端に表示される文字を指定
  call denite#custom#option('default', 'prompt', '>')

  " Deniteの設定
  nnoremap [denite] <Nop>
  nmap <C-f> [denite]

  " -buffer-name=
  nnoremap <silent> [denite]g  :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>

  " filename
  nnoremap <silent> [denite]f  :<C-u>Denite file_rec -buffer-name=search-buffer-denite<CR>

  " Denite grep検索結果を再表示する
  nnoremap <silent> [denite]r :<C-u>Denite -resume -buffer-name=search-buffer-denite<CR>
  " resumeした検索結果の次の行の結果へ飛ぶ
  nnoremap <silent> [denite]n :<C-u>Denite -resume -buffer-name=search-buffer-denite -select=+1 -immediately<CR>
  " resumeした検索結果の前の行の結果へ飛ぶ
  nnoremap <silent> [denite]p :<C-u>Denite -resume -buffer-name=search-buffer-denite -select=-1 -immediately<CR>
  ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>denite>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'html', 'php']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_add = '''
let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript']

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
on_ft = ['javascript']
hook_add = '''
  setl omnifunc=jscomplete#CompleteJS
  if !exists('g:neocomplcache_omni_functions')
    let g:neocomplcache_omni_functions = {}
  endif
  let g:neocomplcache_omni_functions.javascript = 'nodejscomplete#CompleteJS'
  let g:node_usejscomplete = 1
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript']

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set noshowmode
  let g:lightline = {
        \'active': {
        \  'left': [
        \    ['mode', 'paste'],
        \    [ 'gitbranch', 'readonly', 'filename', 'modified' ],
        \    ['ale'],
        \  ],
        \  'right': [
        \    [ 'lineinfo' ],
        \    [ 'percent' ],
        \    [ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex' ],
        \ ],
        \},
        \ 'component': {
        \   'charvaluehex': '0x%B'
        \ },
        \'component_function': {
        \  'ale': 'ALEStatus',
        \  'gitbranch': 'fugitive#head',
        \  'filename': 'LightLineFilename'
        \}
        \ }

  function! LightLineFilename()
    return expand('%')
  endfunction
'''

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]] # コード補完
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft= ['ruby']

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
" ref: https://postd.cc/vim3/
nmap ; :Buffers<CR>
" nmap <Leader>t :Files<CR>
" nmap r :Tags<CR>
'''

[[plugins]]
repo = 'tpope/vim-sleuth'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'mattn/gist-vim'
depends = ['mattn/webapi-vim']

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['godlygeek/tabular']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c']

#tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'mitubaEX/codic-vim'

[[plugins]]
repo = 'zchee/deoplete-go'
