[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:go_fmt_fail_silently = 1
  let g:ale_fix_on_save = 1
  " let g:neomake_javascript_enabled_makers = ['tslint', 'eslint', 'flow']

  " let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
  function! ALEStatus()
    " return ALEGetStatusLine()
    let l:counts = ale#statusline#Count(bufnr(''))

    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors

    return l:counts.total == 0 ? 'OK' : printf(
		    \   '⚠ %d ⨉ %d',
		    \   all_non_errors,
		    \   all_errors
		    \)
  endfunction

  let g:ale_linters = {'javascript': ['eslint', 'prettier'], 'jsx': ['stylelint', 'eslint', 'prettier'], 'tsx': ['tslint', 'prettier'], 'hs': ['hlint'], 'tex': ['alex']}
  let g:ale_linter_aliases = {'jsx': 'css'}
  let g:ale_fixers = {
  \   'python': ['autopep8', 'isort'],
  \   'javascript': ['eslint', 'prettier'],
  \   'typescript': ['tslint', 'prettier'],
  \   'haskell': ['stylish-haskell']
  \}
  let g:ale_fix_on_save = 1
  let g:ale_javascript_prettier_options = '--single-quote --trailing-comma es5'
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 1
  let g:ale_open_list = 1

  " エラーと警告がなくなっても開いたままにする
  " let g:ale_keep_list_window_open = 1
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<denite<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  " 参考:http://replicity.hateblo.jp/entry/2017/06/03/140731
  "
  "C-j,C-kで上下移動
  call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')
  "ESCキーでdeniteを終了
  call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
  call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')

  " C-sでsplit表示
  call denite#custom#map('insert', '<C-s>', '<denite:do_action:vsplit>', 'noremap')

  " tabopen
  call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>', 'noremap')

  " プロンプトの左端に表示される文字を指定
  call denite#custom#option('default', 'prompt', '>')

  " Deniteの設定
  nnoremap [denite] <Nop>
  nmap <C-f> [denite]

  " -buffer-name=
  nnoremap <silent> [denite]g  :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>

  " filename
  nnoremap <silent> [denite]f  :<C-u>Denite file_rec -buffer-name=search-buffer-denite<CR>

  " Denite grep検索結果を再表示する
  nnoremap <silent> [denite]r :<C-u>Denite -resume -buffer-name=search-buffer-denite<CR>
  " resumeした検索結果の次の行の結果へ飛ぶ
  nnoremap <silent> [denite]n :<C-u>Denite -resume -buffer-name=search-buffer-denite -select=+1 -immediately<CR>
  " resumeした検索結果の前の行の結果へ飛ぶ
  nnoremap <silent> [denite]p :<C-u>Denite -resume -buffer-name=search-buffer-denite -select=-1 -immediately<CR>
  ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>denite>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript']
hook_add = '''
let g:deoplete#sources#ternjs#tern_bin = '/usr/local/bin/tern'
let g:deoplete#sources#ternjs#timeout = 1

" Whether to include the types of the completions in the result data. Default: 0
let g:deoplete#sources#ternjs#types = 1

" Whether to include the distance (in scopes for variables, in prototypes for
" properties) between the completions and the origin position in the result
" data. Default: 0
let g:deoplete#sources#ternjs#depths = 1

" Whether to include documentation strings (if found) in the result data.
" Default: 0
let g:deoplete#sources#ternjs#docs = 1

" When on, only completions that match the current word at the given point will
" be returned. Turn this off to get all results, so that you can filter on the
" client side. Default: 1
let g:deoplete#sources#ternjs#filter = 0

" Whether to use a case-insensitive compare between the current word and
" potential completions. Default 0
let g:deoplete#sources#ternjs#case_insensitive = 1

" When completing a property and no completions are found, Tern will use some
" heuristics to try and return some properties anyway. Set this to 0 to
" turn that off. Default: 1
let g:deoplete#sources#ternjs#guess = 0

" Determines whether the result set will be sorted. Default: 1
let g:deoplete#sources#ternjs#sort = 0

" When disabled, only the text before the given position is considered part of
" the word. When enabled (the default), the whole variable name that the cursor
" is on will be included. Default: 1
let g:deoplete#sources#ternjs#expand_word_forward = 0

" Whether to ignore the properties of Object.prototype unless they have been
" spelled out by at least two characters. Default: 1
let g:deoplete#sources#ternjs#omit_object_prototype = 0

" Whether to include JavaScript keywords when completing something that is not
" a property. Default: 0
let g:deoplete#sources#ternjs#include_keywords = 1

" If completions should be returned when inside a literal. Default: 1
let g:deoplete#sources#ternjs#in_literal = 0


"Add extra filetypes
let g:deoplete#sources#ternjs#filetypes = [
                \ 'jsx',
                \ 'javascript.jsx',
                \ 'vue',
                \ ]
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set noshowmode
  let g:lightline = {
        \'active': {
        \  'left': [
        \    ['mode', 'paste'],
        \    [ 'gitbranch', 'readonly', 'filename', 'modified' ],
        \    ['ale'],
        \  ],
        \  'right': [
        \    [ 'lineinfo' ],
        \    [ 'percent' ],
        \    [ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex' ],
        \ ],
        \},
        \ 'component': {
        \   'charvaluehex': '0x%B'
        \ },
        \'component_function': {
        \  'ale': 'ALEStatus',
        \  'gitbranch': 'fugitive#head',
        \  'filename': 'LightLineFilename'
        \}
        \ }

  function! LightLineFilename()
    return expand('%')
  endfunction
'''

[[plugins]] # コード補完
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft= ['ruby']

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
" ref: https://postd.cc/vim3/
nmap ; :Buffers<CR>
" nmap <Leader>t :Files<CR>
" nmap r :Tags<CR>
'''

[[plugins]]
repo = 'tpope/vim-sleuth'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'mattn/gist-vim'
depends = ['mattn/webapi-vim']

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['godlygeek/tabular']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c']

#tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'mitubaEX/codic-vim'

[[plugins]]
repo = 'zchee/deoplete-go'

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
hook_add = '''
let g:deoplete#sources#rust#racer_binary='/usr/local/bin/racer'
let g:deoplete#sources#rust#rust_source_path='/usr/local/Cellar/rust/1.25.0/lib/rustlib/src/rust/src'
'''

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/deoplete-clangx'

[[plugins]]
repo = 'maxbrunsfeld/vim-yankstack'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'ElmCast/elm-vim'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'AndrewRadev/sideways.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['kana/vim-operator-user']
hook_add = '''
" operator mappings
map <silent>sa <Plug>(operator-surround-append)
map <silent>sd <Plug>(operator-surround-delete)
map <silent>sr <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'rhysd/vim-grammarous'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''

let g:startify_lists = [
\ { 'type': 'files',     'header': ['   MRU']            },
  \ { 'type': 'dir',       'header': ['   MRU '. getcwd()] },
  \ { 'type': 'sessions',  'header': ['   Sessions']       },
  \ { 'type': 'bookmarks', 'header': ['   Bookmarks']      },
  \ { 'type': 'commands',  'header': ['   Commands']       },
  \ ]
let g:startify_bookmarks = [ {'c': '~/.config/nvim/init.vim'}, '~/.zshrc' ]
'''

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'kana/vim-smartinput'
hook_add = '''
'''

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'SirVer/ultisnips'
depends = ['honza/vim-snippets']
hook_add = '''
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-l>"
let g:UltiSnipsJumpBackwardTrigger="<c-h>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
'''

[[plugins]]
repo = 'udalov/kotlin-vim'
