[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = ['csv']
hook_source = '''
" for chrisbra/csv
let g:csv_delim=','
let g:csv_highlight_column = 'y'
let g:csv_hiGroup = 'Visual'
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install"'

# :A alternate
# :R related
# :Rails console
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']
hook_add = '''
let g:rubycomplete_rails = 1
'''

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']
hook_add = '''
let g:rubycomplete_buffer_loading = 1
let g:rubycomplete_classes_in_global = 1
'''

[[plugins]]
repo = 'SirVer/ultisnips'
on_ft = ['ruby']
on_event = ['InsertEnter']
hook_add = '''
let g:UltiSnipsExpandTrigger="<c-f>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
'''

[[plugins]]
repo = 'honza/vim-snippets'
on_event = ['InsertEnter']
on_ft = ['ruby']
